CREATE TABLE usuarios (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nome VARCHAR(100) NOT NULL,
                          email VARCHAR(120) NOT NULL UNIQUE,
                          senha VARCHAR(255) NOT NULL,
                          telefone VARCHAR(20),
                          created_at TIMESTAMP,
                          updated_at TIMESTAMP,
                          CONSTRAINT uk_usuario_email UNIQUE (email)
);

CREATE TABLE veiculos (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          usuario_id BIGINT NOT NULL,
                          marca VARCHAR(60) NOT NULL,
                          modelo VARCHAR(60) NOT NULL,
                          ano INTEGER NOT NULL,
                          placa VARCHAR(10) NOT NULL UNIQUE,
                          combustivel VARCHAR(20) NOT NULL,
                          quilometragem_atual BIGINT NOT NULL,
                          created_at TIMESTAMP,
                          updated_at TIMESTAMP,
                          CONSTRAINT uk_veiculo_placa UNIQUE (placa),
                          CONSTRAINT fk_veiculos_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

CREATE TABLE planos_manutencao (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   veiculo_id BIGINT NOT NULL,
                                   tipo VARCHAR(30) NOT NULL,
                                   descricao VARCHAR(150),
                                   intervalo_km BIGINT,
                                   intervalo_dias INTEGER,
                                   ativo BOOLEAN NOT NULL,
                                   created_at TIMESTAMP,
                                   updated_at TIMESTAMP,
                                   CONSTRAINT fk_planos_manutencao_veiculo FOREIGN KEY (veiculo_id) REFERENCES veiculos(id)
);

CREATE TABLE manutencoes (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             veiculo_id BIGINT NOT NULL,
                             plano_id BIGINT,
                             descricao VARCHAR(150) NOT NULL,
                             data DATE NOT NULL,
                             quilometragem BIGINT NOT NULL,
                             valor NUMERIC(10,2) NOT NULL,
                             created_at TIMESTAMP,
                             updated_at TIMESTAMP,
                             CONSTRAINT fk_manutencoes_veiculo FOREIGN KEY (veiculo_id) REFERENCES veiculos(id),
                             CONSTRAINT fk_manutencoes_plano FOREIGN KEY (plano_id) REFERENCES planos_manutencao(id)
);

CREATE TABLE abastecimentos (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                veiculo_id BIGINT NOT NULL,
                                data DATE NOT NULL,
                                tipo_combustivel VARCHAR(20) NOT NULL,
                                valor_total NUMERIC(10,2) NOT NULL,
                                litros NUMERIC(10,2) NOT NULL,
                                valor_litro NUMERIC(10,2) NOT NULL,
                                quilometragem BIGINT NOT NULL,
                                consumo_medio NUMERIC(10,2) NOT NULL,
                                custo_por_km NUMERIC(10,4) NOT NULL,
                                created_at TIMESTAMP,
                                updated_at TIMESTAMP,
                                CONSTRAINT fk_abastecimentos_veiculo FOREIGN KEY (veiculo_id) REFERENCES veiculos(id)
);

CREATE TABLE lembretes (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           veiculo_id BIGINT NOT NULL,
                           titulo VARCHAR(80) NOT NULL,
                           descricao VARCHAR(200),
                           tipo VARCHAR(20) NOT NULL,
                           data_alerta DATE NOT NULL,
                           status VARCHAR(15) NOT NULL,
                           created_at TIMESTAMP,
                           updated_at TIMESTAMP,
                           CONSTRAINT fk_lembretes_veiculo FOREIGN KEY (veiculo_id) REFERENCES veiculos(id)
);

CREATE TABLE refresh_tokens (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                token VARCHAR(512) NOT NULL UNIQUE,
                                usuario_id BIGINT NOT NULL,
                                expires_at TIMESTAMP NOT NULL,
                                revoked BOOLEAN NOT NULL,
                                CONSTRAINT fk_refresh_tokens_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

CREATE TABLE token_blacklist (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 jti VARCHAR(100) NOT NULL UNIQUE,
                                 expires_at TIMESTAMP NOT NULL
);